server:
  port: 9981
app:
  file-upload-path: D:/upload/
  aes-key: 1RR1JeyfUWvy1gmZFoO439Tk43dPdI92C1hZ6Tr2wFo=
  vrs:
    app-id: wx1d42749a3c5ffc1a
    app-secret: f407bf39fb88fb7772f6c8e475b2df40
    wxapp-msg-template-id: Zkft4dkAvJsQTfUoDbkcdqXj2uv80lUx4DBHuhk-69I
  ekp:
    server-url: http://10.0.10.30:9081
    vrs-review-template-id: 19afc51be2886d34c5da13e46ea8b977
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    dynamic:
      druid:
        async-init: true
      primary: local-mysql
      strict: false
      datasource:
        local-mysql:
          url: jdbc:mysql://127.0.0.1:3306/vrs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        ekp-sqlserver:
          url: jdbc:sqlserver://10.0.10.210:1433;DatabaseName=ekp;encrypt=false;trustServerCertificate=true;useSSL=false
          username: sa
          password: win*Coade#..
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 101MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
    enable-sql-runner: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'VRS-BACKEND'
      paths-to-match: '/**'
      packages-to-scan: cn.dong.nexus.modules.vrs.controller.manage
    - group: 'VRS-WXAPP'
      paths-to-match: '/**'
      packages-to-scan: cn.dong.nexus.modules.vrs.controller.wxapp
    - group: 'NEXUS-BOOT'
      paths-to-match: '/**'
      packages-to-scan: cn.dong.nexus.controller
    - group: 'RBAC'
      paths-to-match: '/**'
      packages-to-scan: cn.dong.nexus.modules.rbac
    - group: 'SYSTEM'
      paths-to-match: '/**'
      packages-to-scan: cn.dong.nexus.modules.system

sa-token:
  token-name: Authorization
  timeout: 86400
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: true
  token-prefix: Bearer
  is-read-cookie: false
